export class gestiondenuncia {
    idDenuncia: number = 0;
    noExpediente: string = '';
    nombreDenunciante: string = '';
    estado: number = 0;
    archivado: number = 0;
    fechaAudiencia: Date = null;
    lugar: string = '';
    generalidades: string = '';
    resolucion: string = '';
    idFirmaPresidentejcd: number = 0;
    portalTransparencia: string = '';
    fechaModificacion: Date = null;
    fechaRegistro: Date = null;
    usuarioModificacion: string = '';
    jdc: string = '';
    idFirmaRepresentantecsjjcd: number = 0;
    idFirmaRepresentanteminedjcd: number = 0;
}